version: '2'
services:
  backend:
    build: ./backend
    volumes:
      - "./backend/server.js:/src/server.js"
    ports:
      - '8080:8080'
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - '6379:6379'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]